# Minimal Jekyll configuration for GitHub Pages
url: "http://kjamithash.github.io"
title: "Amithash Kankanallu"
description: "Minimal one‑page personal site with animated mesh‑gradient background."

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile
